version: '3'

services:
  ghost:
    container_name: ghost
    image: ghost:alpine
    restart: always
    hostname: ghost
    environment: # this section can be commented to start in dev mode by default
      - url="http://nkorai.com/"
      - NODE_ENV=production # set either production or development, then it will load the respective config
  rproxy:
    container_name: rproxy
    hostname: rproxy
    image: nginx
    depends_on:
      - "ghost"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./build/nginx/:/etc/nginx"
      - "./build/ssl/private:/etc/ssl/private"
  # letsencrypt:
  #   container_name: letsencrypt
  #   image: gordonchan/auto-letsencrypt
  #   volumes:
  #     - /var/log/letsencrypt/:/var/log/letsencrypt
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/lib/letsencrypt:/var/lib/letsencrypt
  #     - /tmp/letsencrypt/www:/tmp/letsencrypt/www
  #     - /build/ssl/:/etc/nginx/certs
  #   environment:
  #     - EMAIL=nausherwan.korai@gmail.com
  #     - SERVER_CONTAINER=rproxy
  #     - WEBROOT_PATH=/tmp/letsencrypt/www
  #     - CERTS_PATH=/etc/nginx/certs
  #     - DOMAINS=nkorai.com
  #     - CHECK_FREQ=7
  #   restart: unless-stopped
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./build/ddns:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden