version: '3'

services:
  ghost:
    container_name: ghost
    image: ghost:alpine
    restart: always
    hostname: ghost
    environment: # this section can be commented to start in dev mode by default
      - url="http://74.111.98.229/"
      - NODE_ENV=production # set either production or development, then it will load the respective config
  rproxy:
    container_name: rproxy
    hostname: rproxy
    image: nginx
    depends_on:
      - "ghost"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx/conf/nginx:/etc/nginx"
      - "./ssl/private/:/etc/ssl/private"
    links:
      - ghost
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      - CONFIG="{\r\n  \"settings\": [\r\n    {\r\n      \"provider\": \"namecheap\",\r\n      \"domain\": \"nkorai.com\",\r\n      \"host\": \"@\",\r\n      \"password\": \"password\",\r\n      \"provider_ip\": true\r\n    }\r\n  ]\r\n}"
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always