version: '3'

services:
  ghost:
    container_name: ghost
    image: ghost:alpine
    restart: always
    hostname: ghost
    environment: # this section can be commented to start in dev mode by default
      - url="http://74.111.98.229/"
      - NODE_ENV=production # set either production or development, then it will load the respective config
  rproxy:
    container_name: rproxy
    hostname: rproxy
    image: nginx
    depends_on:
      - "ghost"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./build/nginx/conf/nginx:/etc/nginx"
      - "./build/ssl/private/:/etc/ssl/private"
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./build/ddns:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
    restart: always